Training_name: CLOZUK_PGC2noclo
Validation_name: Biobank_3000brains
Pathway_output_directory: ./CLOZUK_PGC2noclo_Biobank_3000brains_output/Pathways/
Gene_output_directory: ./CLOZUK_PGC2noclo_Biobank_3000brains_output/Genes/
Gene_location_filename: NCBI37.3.gene.loc
Gene_regions: both
permutations: 10000
Pathway_annotation: pointeight
calculate_indep_SNPs: FALSE
Random_directory: ./CLOZUK_PGC2noclo_Biobank_3000brains_output/Pathways/Randomised_gene_sets_analysis/
Random_scoring_directory: ./CLOZUK_PGC2noclo_Biobank_3000brains_output/Pathways/Randomised_gene_sets_analysis/Scores/
sample_replace: TRUE
Pathway_names: ./CLOZUK_PGC2noclo_Biobank_3000brains_output/Pathways/Pathway_names.txt
