Training_name: CLOZUKPGC2_NO_COGS
Validation_name: COGS
Pathway_output_directory: ./CLOZUKPGC2_NO_COGS_COGS_output/Pathways/
Gene_output_directory: ./CLOZUKPGC2_NO_COGS_COGS_output/Genes/
Gene_location_filename: NCBI37.3.gene.loc
Gene_regions: both
permutations: 1000
Pathway_annotation: pointeight
calculate_indep_SNPs: FALSE
Random_directory: ./CLOZUKPGC2_NO_COGS_COGS_output/Pathways/Randomised_gene_sets_analysis/
Random_scoring_directory: ./CLOZUKPGC2_NO_COGS_COGS_output/Pathways/Randomised_gene_sets_analysis/Scores/
sample_replace: TRUE
Pathway_names: ./CLOZUKPGC2_NO_COGS_COGS_output/Pathways/Pathway_names.txt
